### ISSUE TITLE
[INTERNAL] Addition of Code Coverage in tests.

### ISSUE THREAD

**Issue by Phoebus** [graphXDoses/Cinematrix#127]
Έτσι όπως δούλευα στα tests είδα για το code coverage. Φαίνεται αρκετά χρήσιμο. Απότι κατάλαβα, σου δίχνει με πράσινο ποιές γραμμές κώδικα έτρεξαν με τα unit tests που έχεις γράψει. Βρήκα το JaCoCo plugin για το Maven το οποίο δημιουργεί reports με code coverage, παρόλα αυτά, επειδή και το Surefire δημιουργεί reports, όταν το πρόσθεσα στο pom.xml γέμισε errors το console. Έψαξα να δω αν γίνεται να έχουμε code coverage με το Surefire αλλά δεν βρήκα κάτι. Αν μας ενδιαφέρει να έχουμε κάτι τέτοιο τότε μπορώ να το κοιτάξω περισσότερο. Πριν αποφασήσουμε όμως αν χρειάζεται θα συνεχίσω να γράφω τα unit tests.

**Comment by graphXDoses** [comment]
@Phoebus  καλο ακουγεται αλλα πραγματικα εαν ειναι μεγαλη φασαρια ισως να μην αξιζει τον χρονο. Δες αν βγαινει πουθενα ευκολα αλλιως ασε.
