### ISSUE TITLE
[INTERNAL] Research για πακέτα στην Java, που παρέχουν χρήσιμα εργαλεία για testing

### ISSUE THREAD

**Issue by Phoebus** [graphXDoses/Cinematrix#32]

**Comment by graphXDoses** [comment]
@Phoebus Εξαιρετική δουλειά! Και το research και το wiki section https://github.com/graphXDoses/Cinematrix/wiki. Μονάχα ίσως θα ήταν καλύτερα να γίνει ένα ακόμα **[INTERNAL]** για τις φωτογραφίες ώστε να μπορεί να γίνει `merge` στο `master` με την δυνατότητα σύμπτυξης (`squash`) σε ένα `commit`.

**Comment by Phoebus** [comment]
> @Phoebus Εξαιρετική δουλειά! Και το research και το wiki section https://github.com/graphXDoses/Cinematrix/wiki. Μονάχα ίσως θα ήταν καλύτερα να γίνει ένα ακόμα **[INTERNAL]** για τις φωτογραφίες ώστε να μπορεί να γίνει `merge` στο `master` με την δυνατότητα σύμπτυξης (`squash`) σε ένα `commit`.
> 
> Επισης ειναι καλο να αποφευγονται τα απευθειας commits στο master. Ακομα και για μικρα πραγματα θελει branches.

Ευχαριστώ! 

Αν κατάλαβα καλά, αυτό που θα ήταν καλό να γίνει είναι ένα νέο internal issue που θα έχει να κάνει με το ανέβασμα όλων των απαραίτητων εικόνων, δημιουργία νέου branch με το αντίστοιχο κουμπί του github μέσα στο issue, και μόλις ανεβάσω τις φωτογραφίες στο νέο branch και σιγουρευτώ ότι λειτουργούν σωστά, commit στο master?

**Comment by graphXDoses** [comment]
Ακριβως! Στο pull request που υστερα εξελισεται σε merge υπαρχουν 3 επιλογες και μια απο αυτες δινει την δυνατοτητα του squash και την εισαγωγη του commit στο master branch.

**Comment by graphXDoses** [comment]
Το [Maven Surefire Plugin | For Maven](https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html), σε συνδυασμο με το [JUnit5](https://junit.org/junit5/) φαινεται να καλυπτει πληρως τις αναγκες του project.
